### ISSUE TITLE
Another tksvg repository

### ISSUE THREAD

**Issue by olebole** [oehhar/tksvg#16] opened 2021-06-06 12:21 UTC
Hi,

I maintain some Tcl/Tk packages for Debian; mainly as dependencies of the  [SAOImageDS9](http://ds9.si.edu/) [package](https://packages.debian.org/source/unstable/saods9); however they are meant for general use as well. In future, SAOImageDS9 will pobably get tksvg as a new dependency. From the author of DS9, @wjoye, I now found another tksvg repository -- https://github.com/wjoye/tksvg which seems to focus on TEA compatibility. Would it be possible to cooperate?

I am asking since I would volunteer to maintain tksvg until Tcl/Tk 8.7 hits Debian mainline; however since I will need it for future DS9 releases, it is required to keep in sync with @wjoye's source.

Thanks for consideration!

Ole

**Comment by auriocus** [comment] 2021-06-06 17:45
Hi Ole,
nice to see that the package is in actual use.
Unfortunately, @wjoye has not forked the repo, but instead reuploaded it, which makes it quite hard  to understand from the diff what he actually did. The commit is not that helpful; also this repo here uses TEA as a build system and should build with 8.5, though admittedly it is not tested often. 
As far as I can see from the diff, he has updated the TEA a little bit and recreated the configure script with a newer versio of autoconf. That is for sure a welcome addition. 

But he seems to have missed the most recent checkins here - some fixes that went into the Tcl core. The repo here is regularly backported from the Tcl 8.7 source by @oehhar . So you should target your question towards @wjoye, if he can instead fork this repository and add his changes, which we will happily integrate as either pull requests or add him as a contributor to this repo.

**Comment by oehhar** [comment] 2021-06-07 06:47
Dear Ole,

great that you care. I am ready to pass it directly to you, thank you.

You may consider my answers here:

[https://github.com/wjoye/tksvg/issues/1]

**Comment by olebole** [comment] 2021-06-07 06:54
@oehhar I am only involved by possibly packaging tksvg for Debian, I do not plan to really contribute here. My only goal with this was to bring you together to find a common solution, which makes it comfortable for me to maintain it as a Debian package.

**Comment by oehhar** [comment] 2021-06-07 06:59
Ole,
thank you for packing it for Debian, that is great.

You are free to act:

   -    send me information or patches what is not working for you.
   -    use the alternate repository

Thank you,
Harald

**Comment by olebole** [comment] 2021-06-07 07:02
"Alternate repositories" is what I am trying to avoid, that's why I hope that you find together :nerd_face:

**Comment by oehhar** [comment] 2021-06-07 07:14
Well, thank you for your initiative, I appreciate.
I am not a git wizard nor I know anything about Debian.
So, without any help, probably nothing will happen from my side.

Thank you again,
Harald

**Comment by olebole** [comment] 2021-06-07 07:18
Debian is just my motivation here, and if there appear problems from the packaging, I will contact you to solve them. However, I would like to have only one "upstream" repository, which ideally is maintained by you and @wjoye together instead of taking one and applying the patches from the other. Also other people would probably benefit from a "canonical" tksvg source repository.

**Comment by wjoye** [comment] 2021-06-07 20:34
Ok, I've removed my original repro and properly forked from here. I don't remember exactly where I had downloaded my original copy. Sorry for the confusion.

I've updated the TEA support in my new repro, but I hesitate to create a pull request:
1. The version of TEA I'm using in SAOImage is from Dec 2018, so its pretty old. But I need to use the same TEA version as in my other tcl/tk packages in DS9.
2. I require some additions to the standard TEA implementation that most people don't need.
3. The only reason for the updated TEA is to support building static stand-alone binaries and cross compiling under Mingw to support Windows.

Ole, from your point of view, I think you can just use this repo as your source, and DS9 should pick up on it fine.

**Comment by oehhar** [comment] 2021-06-08 08:39
Dear William,

I forgot to mention the release policy.
A new release should happen:

   *   if there is a critical issue
   *   if there is a new tk 8.7 release with any changes to TkSVG

The version number may be synchronized to Tk 8.7.x in a later stage (e.g. tksvg 8.7.0 will be released when tk 8.7.0 is released).
So, there may also be version jumps. Compatibility to Tk8.7 is my main priority.

Thank you,
Harald

**Comment by oehhar** [comment] 2021-06-08 09:15
Ole,
by the way, I am sitting here in my home office in Zehlendorf, around 5 km from your work. You find my personal contact on the tcl wiki page "hao".
Today, there was a call to test the new Tk8.7 Alpha 5 release candidates and there is already a lot of input from FreeBSD.
You may also consider to test and contribute. If you don't follow the tcl-core list:
Release candidates for Tcl/Tk 8.7a5 are now available at

https://sourceforge.net/projects/tcl/files/Tcl/8.7a5/

I am most interested in discovering any build failures that make these source distributions unsuitable for making libraries and binaries that can be tested in the many ways people use Tcl and Tk.  Failures of that kind will prevent their release.  If you think you have some other reason, speak up.
DGP
--
Thank you for all,
Harald

**Comment by oehhar** [comment] 2021-11-25 09:42
As the issue is solved or reduced, I am closing the bug here.
Thank you all,
Harald

**Closed by oehhar** 2021-11-25 09:42 UTC
